FROM python:3.8-alpine

RUN apk add build-base

RUN python3 -m pip install --upgrade pip python3 -m pip install -r requirements.txt pip3 install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
