# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

#APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - MARKDOWN_MARKDOWNLINT
# DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
MARKDOWN_DEFAULT_STYLE: markdownlint
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
MARKDOWN_MARKDOWNLINT_RULES_PATH: /
