#!/bin/bash

npx -y broken-link-checker-local@latest ./site -roe | grep 'BROKEN\|Getting links from\|Finished' > out.txt
failures=$(grep -o BROKEN out.txt | wc -l)
cat out.txt
rm out.txt

if [[ $failures -gt 0 ]]
then
    exit 1
else
    exit 0
fi