extends: existence
message: "Don't use language (such as '%s') that defines people by their disability."
level: suggestion
ignorecase: true
tokens:
  - a victim of
  - able-bodied
  - affected by
  - an epileptic
  - crippled
  - disabled
  - dumb
  - handicapped
  - handicaps
  - healthy
  - lame
  - maimed
  - missing a limb
  - mute
  - normal
  - sight-impaired
  - stricken with
  - suffers from
  - vision-impaired
