extends: conditional
message: "'%s' has no definition."
level: suggestion
ignorecase: true
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
- API
- ARPU
- ARPPU
- ASP
- CCPA
- CDN
- CLI
- COPPA
- CPU
- CSS
- CJS
- CSV
- DAU
- DEBUG
- DMA
- DOM
- DPI
- FAQ
- GCC
- GCS
- GDB
- GDPR
- GET
- GPU
- GTK
- GUI
- HTML
- HTTP
- HTTPS
- IDE
- ISO
- JAR
- JSON
- JSX
- LESS
- LLDB
- LTV
- NET
- NOTE
- NVDA
- OSS
- PATH
- PDF
- PHP
- PUT
- POST
- RAM
- REPL
- REST
- RSA
- SCM
- SCSS
- SDK
- SQL
- SSH
- SSL
- SVG
- TBD
- TCP
- TODO
- URI
- URL
- USB
- UTC
- UTF
- UTM
- UUID
- XML
- XSS
- YAML
- YYYY
- ZIP