extends: existence
message: "Don't use '%s'."
# See the A-Z word list
ignorecase: true
level: error
tokens:
  - abortion
  - and so on
  - app(?:lication)s? (?:developer|program)
  - app(?:lication)? file
  - backbone
  - contiguous selection
