extends: substitution
message: "Consider using '%s' instead of '%s'."
ignorecase: true
level: suggestion
action:
  name: replace
swap:
  "approximate(?:ly)?": about
  abundance: plenty
  accelerate: speed up
  accentuate: stress
  accompany: go with
  accomplish: carry out|do
  accorded: given
  accordingly: so
  accrue: add
  acquiesce: agree
  acquire: get|buy
  additional: more|extra
  addressees: you
  adjacent to: next to
  adjustment: change
  admissible: allowed
  advantageous: helpful
  advise: tell
  aggregate: total
  aircraft: plane
  alleviate: ease
  allocate: assign|divide
  alternatively: or
  alternatives: choices|options
  ameliorate: improve
  amend: change
  anticipate: expect
  apparent: clear|plain
  ascertain: discover|find out
  assistance: help
  attain: meet
  attempt: try
  belated: late
  bestow: give
  cease: stop|end
  collaborate: work together
  commence: begin
  compensate: pay
  comprise: form|include
  concept: idea
  concerning: about
  confer: give|award
  consequently: so
  consolidate: merge
  constitutes: forms
  convene: meet
  demonstrate: show|prove
  depart: leave
  designate: choose
  desire: want|wish
  determine: decide|find
  detrimental: bad|harmful
  disclose: share|tell
  discontinue: stop
  disseminate: send|give
  eliminate: end
  elucidate: explain
  employ: use
  enclosed: inside|included
  encounter: meet
  endeavor: try
  enumerate: count
  equitable: fair
  equivalent: equal
  exclusively: only
  expedite: hurry
  facilitate: ease
  females: women
  finalize: complete|finish
  frequently: often
  identical: same
  incorrect: wrong
  indication: sign
  initiate: start|begin
  itemized: listed
  jeopardize: risk
  liaise: work with|partner with
  maintain: keep|support
  methodology: method
  necessitate: cause
  notify: tell
  numerous: many
  obligate: bind|compel
  optimum: best|most
  permit: let
  portion: part
  possess: own
  previously: before
  prioritize: rank
  procure: buy
  provide: give|offer
  purchase: buy
  relocate: move
  solicit: request
  state-of-the-art: latest
  subsequent: later|next
  substantial: large
  sufficient: enough
  terminate: end
  transmit: send
  utilization: use
  utilize: use
