extends: existence
message: "Don't use gerunds in headings."
level: suggestion
scope: heading
raw:
  - \w+ing\b
exceptions: 
  - Tracking
  - tracking
  - Getting
  - Naming
  - preexisting
  - Timing
  - streaming
  - syncing
  - Filtering
  - filtering
  - recurring
  - Recurring
  - Marketing
  - marketing