extends: existence
message: "Don't use end punctuation in headings."
nonword: true
level: suggestion
scope: heading
action:
  name: edit
  params:
    - remove
    - '.?!'
tokens:
  - '[a-z][.?!](?:\s|$)'
