extends: capitalization
message: "'%s' should use sentence-style capitalization."
level: suggestion
scope: heading
match: $sentence
indicators:
  - ':'
exceptions:
  - Azure
  - Audiences
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - I
  - Node
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MongoDB
  - REPL
  - Studio
  - TypeScript
  - URLs
  - Visual
  - VS
  - Windows
  - API
  - Amplitude
  - Recommend 
  - Experiment
  - Middleware
  - ID
  - IDs 
