extends: existence
message: "Use 'to' instead of a dash in '%s'."
nonword: true
level: error
action:
  name: edit
  params:
    - replace
    - '[-–]'
    - 'to'
tokens:
  - '\b(?:AM|PM)\s?[-–]\s?.+(?:AM|PM)\b'
