extends: existence
message: "Don't spell out the number in '%s'."
level: error
raw:
  - '[a-zA-Z]+\s'
tokens:
  - '(?:centi|milli)?meters'
  - '(?:kilo)?grams'
  - '(?:kilo)?meters'
  - '(?:mega)?pixels'
  - cm
  - inches
  - lb
  - miles
  - pounds
