name: Bug Report
description: Report a documenation bug on the Amplitude Developer Center. If you're having issues with the product, ask for help in the [Amplitude Community](https://community.amplitude.com)
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - amplitude-dev-docs
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with the Amplitude Developer Center site
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what the problem is. Please be as specific as possible. Note -- We can't help you troubleshoot product problems. If you're having a problem with a product, ask for help in the Amplitude Community at https://community.amplitude.com
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
