---
# MegaLinter GitHub Action configuration file for our daily link check.
# This action runs a link check on our entire doc set every day at 12:00 AM so we're warned when a link breaks.
# This is a separate workflow file from main Megalinter checks because we needed to use different settings for this run.

name: Daily Link Check
on:
  schedule:
  # Run everyday at 12:00 AM
  - cron: "0 0 * * *"

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Setup Node
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      # External Link Check
      - name: Internal Link Check
        run: ./linkchecker external
